export const SET_USER = 'SET_USER'
export const SET_TOKEN = 'SET_TOKEN'
export const SET_LOGED = 'SET_LOGED'
export const SET_LOGININ = 'SET_LOGININ'
export const ADD_CART = 'ADD_CART'
export const ADD_PRODUCT = 'ADD_PRODUCT'
